apiVersion: v1
kind: Service
metadata:
  name: devops-app-service
  namespace: devops-app
  labels:
    app: devops-app
spec:
  selector:
    app: devops-app
  ports:
    - port: 80           # Port exposed externally
      targetPort: 8080   # Port your app listens on inside the container
      protocol: TCP
  type: LoadBalancer      # <-- changed from ClusterIP to LoadBalancer
